# -*- coding: utf-8 -*-
"""Mood-Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGnMDdTzfY5EwTY0GSRB8AatCbt8AqnN
"""

!pip install matplotlib ipywidgets requests

import matplotlib.pyplot as plt
from ipywidgets import interact, widgets
import random
import requests
from IPython.display import display, HTML, clear_output

motivational_quotes = [
    "Believe you can and you're halfway there. –Theodore Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. –Winston Churchill",
    "Act as if what you do makes a difference. It does. –William James",
    "The only way to do great work is to love what you do. –Steve Jobs",
    "You are never too old to set another goal or to dream a new dream. –C.S. Lewis"
]

jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why was the math book sad? It had too many problems.",
    "What do you call fake spaghetti? An impasta!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "I told my computer I needed a break, and now it won't stop sending me Kit-Kats."
]

relaxing_videos = [
    "https://www.youtube.com/watch?v=5qap5aO4i9A",  # Lofi beats
    "https://www.youtube.com/watch?v=lTRiuFIWV54",  # Nature sounds
    "https://www.youtube.com/watch?v=2OEL4P1Rz04",  # Fireplace
    "https://www.youtube.com/watch?v=xfr64zoBTAQ",  # Calm piano
    "https://www.youtube.com/watch?v=AYvR4hEIwoo"   # Ocean waves
]

def mood_dashboard(mood):
    clear_output(wait=True)

    print(f"🌟 Your Current Mood: {mood.capitalize()} 🌟")

    if mood == "happy":
        activity = "Keep spreading the joy! Here's a motivational quote:"
        suggestion = random.choice(motivational_quotes)
    elif mood == "sad":
        activity = "Cheer up with this joke:"
        suggestion = random.choice(jokes)
    elif mood == "relaxed":
        activity = "Enjoy this relaxing video:"
        suggestion = f"Watch this: [Relaxing Video]({random.choice(relaxing_videos)})"
    elif mood == "stressed":
        activity = "Take a deep breath and enjoy this:"
        suggestion = f"Watch this: [Relaxing Video]({random.choice(relaxing_videos)})"
    else:
        activity = "Here's something random to lighten your day:"
        suggestion = random.choice(jokes + motivational_quotes)

    print(f"\n📝 {activity}")
    print(f"👉 {suggestion}")

    moods = ["happy", "sad", "relaxed", "stressed", "neutral"]
    mood_counts = [random.randint(10, 100) for _ in moods]
    mood_counts[moods.index(mood)] += random.randint(5, 20)

    plt.figure(figsize=(8, 5))
    plt.bar(moods, mood_counts, color="skyblue", alpha=0.8)
    plt.title("Mood Distribution", fontsize=16)
    plt.xlabel("Mood", fontsize=12)
    plt.ylabel("Count", fontsize=12)
    plt.xticks(fontsize=10)
    plt.yticks(fontsize=10)
    plt.show()

mood_selector = widgets.Dropdown(
    options=["happy", "sad", "relaxed", "stressed", "neutral"],
    description="Your Mood:",
    style={"description_width": "initial"}
)

interact(mood_dashboard, mood=mood_selector)

